"""
IntruTrace – incident report export (P2).
Turns the incident-detail API object (same shape from memory or Postgres) into a standalone
Markdown report an analyst can attach to a ticket: story, timeline, alerts, raw evidence lines.
Owner: Bhanu Prasad
"""

from typing import Any, Dict, List

MAX_EVIDENCE_LINES_PER_ALERT = 20
TAIL_LINES = 5  # long evidence keeps its last lines: that's where the success / sudo / download is


def _fmt_ts(ts: str) -> str:
    return ts.replace("T", " ").replace("Z", " UTC")


def incident_markdown(analysis_id: str, d: Dict[str, Any]) -> str:
    ents = d["entities"]
    lines: List[str] = [
        f"# Incident {d['id']}: {d['title']}",
        "",
        f"- **Level:** {d['level'].upper()} (risk {d['risk_score']}/100)",
        f"- **Time span:** {_fmt_ts(d['start'])} → {_fmt_ts(d['end'])}",
        f"- **IPs:** {', '.join(ents['ips']) or '-'}",
        f"- **Users:** {', '.join(ents['users']) or '-'}",
        f"- **Kill-chain stages:** {' → '.join(d['stages'])}",
        f"- **Analysis:** {analysis_id}",
        "",
        "## Assessment",
        "",
        d["summary"].removeprefix("Assessment: "),
        "",
        "## Attack story",
        "",
    ]
    for n, step in enumerate(d["story"], start=1):
        lines.append(f"{n}. **{_fmt_ts(step['ts'])}** [{step['stage']}] {step['text']}")
    lines += ["", "## Recommended response", ""]
    lines += [f"- {r.strip()}" for r in d["recommendation"].rstrip(".").split(". ") if r.strip()]
    lines += ["", "## Alerts and evidence", ""]

    evidence = d.get("evidence", {})
    for a in d["alerts"]:
        lines += [
            f"### {a['id']} · {a['rule_id']} {a['rule_name']} ({a['severity']}, {a['mitre']['technique']})",
            "",
            f"{a['reason']}",
            "",
            f"Evidence: {len(a['evidence_event_ids'])} log line(s)"
            + (f", first {MAX_EVIDENCE_LINES_PER_ALERT - TAIL_LINES} and last {TAIL_LINES} shown"
               if len(a["evidence_event_ids"]) > MAX_EVIDENCE_LINES_PER_ALERT else ""),
            "",
            "```",
        ]
        ids = a["evidence_event_ids"]
        if len(ids) > MAX_EVIDENCE_LINES_PER_ALERT:
            head = MAX_EVIDENCE_LINES_PER_ALERT - TAIL_LINES
            ids = ids[:head] + [None] + ids[-TAIL_LINES:]
        for eid in ids:
            if eid is None:
                lines.append(f"... {len(a['evidence_event_ids']) - MAX_EVIDENCE_LINES_PER_ALERT} more line(s) omitted ...")
            elif (ev := evidence.get(eid)):
                lines.append(f"{ev['file']}:{ev['line_no']}  {ev['raw']}")
        lines += ["```", ""]

    lines.append("_Generated by IntruTrace: deterministic rules, every claim backed by raw log lines. "
                 "Signature matches and large transfers are indicators, not confirmed compromise._")
    return "\n".join(lines) + "\n"
